export const BANKS = [
  { name: "Access Bank",                            code: "044" },
  { name: "Citibank Nigeria",                       code: "023" },
  { name: "Ecobank Nigeria",                        code: "050" },
  { name: "Fidelity Bank",                          code: "070" },
  { name: "First Bank of Nigeria",                  code: "011" },
  { name: "First City Monument Bank (FCMB)",        code: "214" },
  { name: "Globus Bank",                            code: "103" },
  { name: "Guaranty Trust Bank (GTB)",              code: "058" },
  { name: "Heritage Bank",                          code: "030" },
  { name: "Keystone Bank",                          code: "082" },
  { name: "Polaris Bank",                           code: "076" },
  { name: "Providus Bank",                          code: "101" },
  { name: "Stanbic IBTC Bank",                      code: "221" },
  { name: "Standard Chartered Bank",                code: "068" },
  { name: "Sterling Bank",                          code: "232" },
  { name: "SunTrust Bank",                          code: "100" },
  { name: "Titan Trust Bank",                       code: "102" },
  { name: "Union Bank",                             code: "032" },
  { name: "United Bank for Africa (UBA)",           code: "033" },
  { name: "Unity Bank",                             code: "215" },
  { name: "Wema Bank",                              code: "035" },
  { name: "Zenith Bank",                            code: "057" },

  // Microfinance & Digital Banks
  { name: "Kuda Bank",                              code: "090267" },
  { name: "Opay",                                   code: "999992" },
  { name: "Palmpay",                                code: "999991" },
  { name: "Moniepoint MFB",                         code: "50515" },
  { name: "Carbon (One Finance)",                   code: "565" },
  { name: "VFD Microfinance Bank",                  code: "566" },
  { name: "Fairmoney Microfinance Bank",            code: "51318" },
  { name: "Sparkle Microfinance Bank",              code: "51310" },
  { name: "Mint MFB (Mint-Finex)",                  code: "50304" },
  { name: "Rubies MFB",                             code: "125" },
  { name: "Raven Bank",                             code: "50114" },
  { name: "Trustbанк (Trustbanc MFB)",              code: "090270" },
  { name: "Accion MFB",                             code: "602" },
  { name: "Covenant MFB",                           code: "120" },
  { name: "Ekondo MFB",                             code: "562" },
  { name: "Empire Trust MFB",                       code: "090114" },
  { name: "Eyowo",                                  code: "50126" },
  { name: "Gomoney",                                code: "100022" },
  { name: "Hasal MFB",                              code: "090121" },
  { name: "Ibile MFB",                              code: "090115" },
  { name: "Infinity MFB",                           code: "50457" },
  { name: "Lagos Building Investment Company (LBIC)",code: "090177" },
  { name: "Lapo MFB",                               code: "090177" },
  { name: "Letshego MFB",                           code: "090159" },
  { name: "Links MFB",                              code: "090269" },
  { name: "Lotus Bank",                             code: "303" },
  { name: "Mainstreet MFB",                         code: "090171" },
  { name: "Mutual Trust MFB",                       code: "090128" },
  { name: "NPF MFB",                                code: "090177" },
  { name: "Pagemakers MFB",                         code: "090282" },
  { name: "PatrickGold MFB",                        code: "090317" },
  { name: "Peace MFB",                              code: "090132" },
  { name: "Pecantrust MFB",                         code: "090137" },
  { name: "Personal Trust MFB",                     code: "090135" },
  { name: "Petra MFB",                              code: "090165" },
  { name: "Platinum MFB",                           code: "090355" },
  { name: "Refuge MFB",                             code: "090138" },
  { name: "Regent MFB",                             code: "090139" },
  { name: "Rephidim MFB",                           code: "090322" },
  { name: "Richway MFB",                            code: "090132" },
  { name: "Safe Haven MFB",                         code: "090286" },
  { name: "Seed Capital MFB",                       code: "090112" },
  { name: "Stellas MFB",                            code: "090262" },
  { name: "Tanadi MFB",                             code: "090134" },
  { name: "Tangerine Money (formerly 9PSB)",        code: "120001" },
  { name: "TCF MFB",                                code: "090115" },
  { name: "Unical MFB",                             code: "090193" },
  { name: "Verdant MFB",                            code: "090140" },
  { name: "Xslnce MFB",                             code: "090124" },
  { name: "Yes MFB",                                code: "090142" },

  // Mobile Money / Fintech
  { name: "9Payment Service Bank (9PSB)",           code: "120001" },
  { name: "Paga",                                   code: "100002" },
  { name: "Paycom (Opay alternate)",                code: "100004" },
  { name: "Quickteller Paypoint",                   code: "100005" },
  { name: "Teasy Mobile",                           code: "100010" },
  { name: "Cellulant",                              code: "100005" },
  { name: "eTranzact",                              code: "100006" },
  { name: "Interswitch Limited",                    code: "100006" },
  { name: "Moniba MFB",                             code: "090179" },
  { name: "Bankly MFB",                             code: "090435" },
  { name: "Brass MFB",                              code: "090578" },
  { name: "FSDH Merchant Bank",                     code: "501" },
  { name: "Greenwich Merchant Bank",                code: "562" },
  { name: "Rand Merchant Bank",                     code: "502" },
  { name: "Nova Merchant Bank",                     code: "561" },
  { name: "Coronation Merchant Bank",               code: "559" },
  { name: "Jaiz Bank",                              code: "301" },
  { name: "Taj Bank",                               code: "302" },
].sort((a, b) => a.name.localeCompare(b.name));

export const MOCK_TRANSACTIONS = [
  { id: 1, type: "credit", label: "Commission – 45 Bourdillon Road",    amount: 250000, date: "Feb 28, 2026", status: "completed" },
  { id: 2, type: "debit",  label: "Withdrawal to GTB ****4521",         amount: 100000, date: "Feb 22, 2026", status: "completed" },
  { id: 3, type: "credit", label: "Commission – Lekki Phase 1 Duplex",  amount: 180000, date: "Feb 15, 2026", status: "completed" },
  { id: 4, type: "credit", label: "Agency Fee – 3BR Flat Ikeja",        amount:  75000, date: "Feb 10, 2026", status: "completed" },
  { id: 5, type: "debit",  label: "Withdrawal to Zenith ****8830",      amount:  50000, date: "Jan 30, 2026", status: "completed" },
  { id: 6, type: "credit", label: "Commission – VI Penthouse",          amount: 420000, date: "Jan 18, 2026", status: "completed" },
];

export const fmt = (n) =>
  "₦" + Number(n).toLocaleString("en-NG", { minimumFractionDigits: 2 });