export const MOCK_PROPERTIES = [
    {
      _id: "1", title: "3 Bedroom Duplex", location: "Victoria Island, Lagos",
      city: "Victoria Island", price: 2500000, type: "rent", propertyType: "Duplex",
      bedrooms: 3, bathrooms: 2, sqft: 1800, yearBuilt: 2019, parking: 2,
      videoUrl: null,
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1400&q=85",
      agent: { name: "Emeka Okafor", avatar: "https://i.pravatar.cc/80?img=11", phone: "09076291234" },
      description: "A beautifully finished 3-bedroom duplex nestled in the heart of Victoria Island. Features contemporary finishes, spacious rooms, fitted kitchen, and a private garden.",
      features: ["Swimming Pool", "24/7 Security", "Generator", "Fitted Kitchen", "CCTV", "Water Treatment", "Boys Quarters", "Air Conditioning"],
      address: "Plot 14, Akin Adesola Street, Victoria Island, Lagos",
    },
    {
      _id: "2", title: "Modern 2-Bedroom Flat", location: "Lekki Phase 1, Lagos",
      city: "Lekki", price: 1800000, type: "rent", propertyType: "Flat",
      bedrooms: 2, bathrooms: 2, sqft: 1200, yearBuilt: 2021, parking: 1,
      videoUrl: null,
      image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1400&q=85",
      agent: { name: "Ngozi Adeyemi", avatar: "https://i.pravatar.cc/80?img=22", phone: "09076295678" },
      description: "A sleek and modern 2-bedroom flat in the sought-after Lekki Phase 1. The property boasts open-plan living, premium finishes, and excellent security.",
      features: ["Gym", "24/7 Security", "Generator", "Fitted Kitchen", "Swimming Pool", "CCTV", "Parking"],
      address: "Block 7, Admiralty Way, Lekki Phase 1, Lagos",
    },
    {
      _id: "3", title: "5 Bedroom Mansion", location: "Ikoyi, Lagos",
      city: "Ikoyi", price: 85000000, type: "sale", propertyType: "Mansion",
      bedrooms: 5, bathrooms: 4, sqft: 4500, yearBuilt: 2018, parking: 4,
      videoUrl: null,
      image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1400&q=85",
      agent: { name: "Femi Adedayo", avatar: "https://i.pravatar.cc/80?img=33", phone: "09076297890" },
      description: "An extraordinary 5-bedroom mansion in the exclusive Ikoyi enclave. This grand residence features a private cinema, rooftop terrace, infinity pool, and world-class finishes throughout.",
      features: ["Private Cinema", "Infinity Pool", "Rooftop Terrace", "Smart Home", "Generator", "24/7 Security", "6 Car Garage", "Elevator", "Wine Cellar"],
      address: "12 Bourdillon Road, Old Ikoyi, Lagos",
    },
    {
      _id: "4", title: "Studio Apartment", location: "Yaba, Lagos",
      city: "Yaba", price: 650000, type: "rent", propertyType: "Apartment",
      bedrooms: 1, bathrooms: 1, sqft: 500, yearBuilt: 2020, parking: 1,
      videoUrl: null,
      image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1400&q=85",
      agent: { name: "Amara Eze", avatar: "https://i.pravatar.cc/80?img=44", phone: "09076291111" },
      description: "A compact and efficiently designed studio apartment in Yaba — Lagos' creative and tech hub. Perfect for young professionals, students, and remote workers.",
      features: ["24/7 Security", "Generator", "CCTV", "Water Supply", "Parking"],
      address: "15 Commercial Avenue, Sabo, Yaba, Lagos",
    },
    {
      _id: "5", title: "4 Bedroom Terrace", location: "Ajah, Lagos",
      city: "Ajah", price: 45000000, type: "sale", propertyType: "Terrace",
      bedrooms: 4, bathrooms: 3, sqft: 2800, yearBuilt: 2022, parking: 2,
      videoUrl: null,
      image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1400&q=85",
      agent: { name: "Tunde Bello", avatar: "https://i.pravatar.cc/80?img=55", phone: "09076292222" },
      description: "A stunning 4-bedroom terrace house in a serene gated estate in Ajah. Built to the highest standard with Italian tiles, fitted wardrobes, and a beautiful garden.",
      features: ["Gated Estate", "Swimming Pool", "Generator", "24/7 Security", "Fitted Kitchen", "CCTV", "Parking"],
      address: "Greenfield Estate, Abraham Adesanya, Ajah, Lagos",
    },
    {
      _id: "6", title: "Mini Flat (Self-Contain)", location: "Surulere, Lagos",
      city: "Surulere", price: 480000, type: "rent", propertyType: "Flat",
      bedrooms: 1, bathrooms: 1, sqft: 420, yearBuilt: 2018, parking: 1,
      videoUrl: null,
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1400&q=85",
      agent: { name: "Chioma Nwosu", avatar: "https://i.pravatar.cc/80?img=66", phone: "09076293333" },
      description: "A well-maintained self-contained mini flat in the heart of Surulere. Close to National Stadium, major markets, and excellent transport links.",
      features: ["Security", "Water Supply", "Parking", "Generator"],
      address: "22 Adeleke Street, Surulere, Lagos",
    },
    {
      _id: "7", title: "3 Bedroom Bungalow", location: "Magodo, Lagos",
      city: "Magodo", price: 38000000, type: "sale", propertyType: "Bungalow",
      bedrooms: 3, bathrooms: 2, sqft: 1600, yearBuilt: 2017, parking: 2,
      videoUrl: null,
      image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1400&q=85",
      agent: { name: "Lanre Ogundimu", avatar: "https://i.pravatar.cc/80?img=7", phone: "09076294444" },
      description: "A charming 3-bedroom detached bungalow set in the peaceful Magodo estate. Features a large compound, covered carport, and well-maintained garden.",
      features: ["Large Compound", "24/7 Security", "Generator", "Garden", "CCTV", "Water Treatment"],
      address: "Plot 6, Magodo Phase 2, Lagos",
    },
    {
      _id: "8", title: "Luxury Penthouse", location: "Eko Atlantic, Lagos",
      city: "Eko Atlantic", price: 12000000, type: "rent", propertyType: "Penthouse",
      bedrooms: 4, bathrooms: 3, sqft: 3200, yearBuilt: 2023, parking: 3,
      videoUrl: null,
      image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1400&q=85",
      agent: { name: "Sandra Igwe", avatar: "https://i.pravatar.cc/80?img=8", phone: "09076295555" },
      description: "The pinnacle of luxury living — a jaw-dropping penthouse on the top floor of one of Eko Atlantic City's premier towers. Featuring panoramic ocean views and the finest finishes.",
      features: ["Panoramic Ocean View", "Private Terrace", "Smart Home", "Concierge", "Infinity Pool", "Gym", "24/7 Security", "Private Elevator", "Wine Room"],
      address: "Eko Pearl Towers, Eko Atlantic City, Lagos",
    },
  ];